{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}


package:
  name: access-med-tools
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/a/access-med-utils/access_med_utils-{{ version }}.tar.gz"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - versioneer
  run:
    - python>=3.9
    - argparse
    - numpy
    - pyyaml
    - dask
    - xarray
    - netcdf4

about:
  home: https://github.com/ACCESS-NRI/med-utils
  license: Apache Software
  license_family: APACHE
  summary: "ACCESS-MED Utilities"
  doc_url: https://github.com/ACCESS-NRI/med-utils

extra:
  recipe-maintainers:
    - rbeucher
